/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IVanillaV1MigrationState,
  IVanillaV1MigrationStateInterface,
} from "../IVanillaV1MigrationState";

const _abi = [
  {
    inputs: [],
    name: "MigrationStateUpdateDisabled",
    type: "error",
  },
  {
    inputs: [],
    name: "UnauthorizedAccess",
    type: "error",
  },
  {
    inputs: [],
    name: "blockNumber",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "conversionDeadline",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stateRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "newStateRoot",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "blockNum",
        type: "uint64",
      },
    ],
    name: "updateConvertibleState",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "proof",
        type: "bytes32[]",
      },
      {
        internalType: "address",
        name: "tokenOwner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "verifyEligibility",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IVanillaV1MigrationState__factory {
  static readonly abi = _abi;
  static createInterface(): IVanillaV1MigrationStateInterface {
    return new utils.Interface(_abi) as IVanillaV1MigrationStateInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVanillaV1MigrationState {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IVanillaV1MigrationState;
  }
}
