/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IVanillaV1Router02,
  IVanillaV1Router02Interface,
} from "../IVanillaV1Router02";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "eth",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "TokensPurchased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "eth",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "profit",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
    ],
    name: "TokensSold",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            internalType: "bool",
            name: "useWETH",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "numEth",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "numToken",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "blockTimeDeadline",
            type: "uint256",
          },
          {
            internalType: "uint24",
            name: "fee",
            type: "uint24",
          },
        ],
        internalType: "struct IVanillaV1Router02.OrderData",
        name: "buyOrder",
        type: "tuple",
      },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "epoch",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "numEth",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "numTokensSold",
        type: "uint256",
      },
    ],
    name: "estimateReward",
    outputs: [
      {
        internalType: "uint256",
        name: "avgBlock",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "htrs",
        type: "uint256",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "uint256",
                name: "price",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "twapPeriodInSeconds",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "profitablePrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "maxProfitablePrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "rewardableProfit",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "reward",
                type: "uint256",
              },
            ],
            internalType: "struct IVanillaV1Router02.TradeResult",
            name: "low",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "price",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "twapPeriodInSeconds",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "profitablePrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "maxProfitablePrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "rewardableProfit",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "reward",
                type: "uint256",
              },
            ],
            internalType: "struct IVanillaV1Router02.TradeResult",
            name: "medium",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "price",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "twapPeriodInSeconds",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "profitablePrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "maxProfitablePrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "rewardableProfit",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "reward",
                type: "uint256",
              },
            ],
            internalType: "struct IVanillaV1Router02.TradeResult",
            name: "high",
            type: "tuple",
          },
        ],
        internalType: "struct IVanillaV1Router02.RewardEstimate",
        name: "estimate",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "execute",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "executePayable",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "nextVersion",
        type: "address",
      },
    ],
    name: "migratePosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "safeList",
    outputs: [
      {
        internalType: "contract IVanillaV1Safelist01",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            internalType: "bool",
            name: "useWETH",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "numEth",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "numToken",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "blockTimeDeadline",
            type: "uint256",
          },
          {
            internalType: "uint24",
            name: "fee",
            type: "uint24",
          },
        ],
        internalType: "struct IVanillaV1Router02.OrderData",
        name: "sellOrder",
        type: "tuple",
      },
    ],
    name: "sell",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "tokenPriceData",
    outputs: [
      {
        internalType: "uint256",
        name: "weightedBlockSum",
        type: "uint256",
      },
      {
        internalType: "uint112",
        name: "ethSum",
        type: "uint112",
      },
      {
        internalType: "uint112",
        name: "tokenSum",
        type: "uint112",
      },
      {
        internalType: "uint32",
        name: "latestBlock",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vnlContract",
    outputs: [
      {
        internalType: "contract IVanillaV1Token02",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "withdrawTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IVanillaV1Router02__factory {
  static readonly abi = _abi;
  static createInterface(): IVanillaV1Router02Interface {
    return new utils.Interface(_abi) as IVanillaV1Router02Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVanillaV1Router02 {
    return new Contract(address, _abi, signerOrProvider) as IVanillaV1Router02;
  }
}
