/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IVanillaV1Safelist01,
  IVanillaV1Safelist01Interface,
} from "../IVanillaV1Safelist01";

const _abi = [
  {
    inputs: [],
    name: "UnauthorizedAccess",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address[]",
        name: "tokens",
        type: "address[]",
      },
    ],
    name: "TokensAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address[]",
        name: "tokens",
        type: "address[]",
      },
    ],
    name: "TokensRemoved",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "isSafelisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextVersion",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IVanillaV1Safelist01__factory {
  static readonly abi = _abi;
  static createInterface(): IVanillaV1Safelist01Interface {
    return new utils.Interface(_abi) as IVanillaV1Safelist01Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVanillaV1Safelist01 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IVanillaV1Safelist01;
  }
}
