/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IVanillaV1ConverterInterface extends ethers.utils.Interface {
  functions: {
    "checkEligibility(bytes32[])": FunctionFragment;
    "convertVNL(bytes32[])": FunctionFragment;
    "migrationState()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkEligibility",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "convertVNL",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "migrationState",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "checkEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "convertVNL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "migrationState",
    data: BytesLike
  ): Result;

  events: {
    "VNLConverted(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "VNLConverted"): EventFragment;
}

export class IVanillaV1Converter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IVanillaV1ConverterInterface;

  functions: {
    checkEligibility(
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<
      [boolean, boolean] & { convertible: boolean; transferable: boolean }
    >;

    convertVNL(
      proof: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    migrationState(overrides?: CallOverrides): Promise<[string]>;
  };

  checkEligibility(
    proof: BytesLike[],
    overrides?: CallOverrides
  ): Promise<
    [boolean, boolean] & { convertible: boolean; transferable: boolean }
  >;

  convertVNL(
    proof: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  migrationState(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    checkEligibility(
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<
      [boolean, boolean] & { convertible: boolean; transferable: boolean }
    >;

    convertVNL(proof: BytesLike[], overrides?: CallOverrides): Promise<void>;

    migrationState(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    VNLConverted(
      converter?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { converter: string; amount: BigNumber }
    >;
  };

  estimateGas: {
    checkEligibility(
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertVNL(
      proof: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    migrationState(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    checkEligibility(
      proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertVNL(
      proof: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    migrationState(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
