/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface VanillaV1MigrationStateInterface extends ethers.utils.Interface {
  functions: {
    "blockNumber()": FunctionFragment;
    "conversionDeadline()": FunctionFragment;
    "stateRoot()": FunctionFragment;
    "updateConvertibleState(bytes32,uint64)": FunctionFragment;
    "verifyEligibility(bytes32[],address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "blockNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "conversionDeadline",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "stateRoot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateConvertibleState",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEligibility",
    values: [BytesLike[], string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "blockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conversionDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stateRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateConvertibleState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEligibility",
    data: BytesLike
  ): Result;

  events: {};
}

export class VanillaV1MigrationState extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: VanillaV1MigrationStateInterface;

  functions: {
    blockNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    conversionDeadline(overrides?: CallOverrides): Promise<[BigNumber]>;

    stateRoot(overrides?: CallOverrides): Promise<[string]>;

    updateConvertibleState(
      newStateRoot: BytesLike,
      blockNum: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    verifyEligibility(
      proof: BytesLike[],
      tokenOwner: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  blockNumber(overrides?: CallOverrides): Promise<BigNumber>;

  conversionDeadline(overrides?: CallOverrides): Promise<BigNumber>;

  stateRoot(overrides?: CallOverrides): Promise<string>;

  updateConvertibleState(
    newStateRoot: BytesLike,
    blockNum: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  verifyEligibility(
    proof: BytesLike[],
    tokenOwner: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    blockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    conversionDeadline(overrides?: CallOverrides): Promise<BigNumber>;

    stateRoot(overrides?: CallOverrides): Promise<string>;

    updateConvertibleState(
      newStateRoot: BytesLike,
      blockNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    verifyEligibility(
      proof: BytesLike[],
      tokenOwner: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    blockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    conversionDeadline(overrides?: CallOverrides): Promise<BigNumber>;

    stateRoot(overrides?: CallOverrides): Promise<BigNumber>;

    updateConvertibleState(
      newStateRoot: BytesLike,
      blockNum: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    verifyEligibility(
      proof: BytesLike[],
      tokenOwner: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    blockNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    conversionDeadline(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stateRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateConvertibleState(
      newStateRoot: BytesLike,
      blockNum: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    verifyEligibility(
      proof: BytesLike[],
      tokenOwner: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
